#!/usr/bin/env python
import socket
import itertools
import sys

from dm_reg import *
from dm_utils import *
from openocd import *

if __name__ == "__main__":
    with OpenOcd(verbose=False) as ocd:
        ocd.dmi_read_fields(dmstatus)
