#!/usr/bin/env python3
import socket
import itertools
import sys

from dm_reg import *
from dm_utils import *
from openocd import *

if __name__ == "__main__":
    with OpenOcd() as ocd:
        ocd.dmi_read_fields(haltsum0)
