set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[7]}]

set_property PACKAGE_PIN AG14 [get_ports {led[0]}]
set_property PACKAGE_PIN AF13 [get_ports {led[1]}]
set_property PACKAGE_PIN AE13 [get_ports {led[2]}]
set_property PACKAGE_PIN AJ14 [get_ports {led[3]}]
set_property PACKAGE_PIN AJ15 [get_ports {led[4]}]
set_property PACKAGE_PIN AH13 [get_ports {led[5]}]
set_property PACKAGE_PIN AH14 [get_ports {led[6]}]
set_property PACKAGE_PIN AL12 [get_ports {led[7]}]


create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list zynq_soc_i/clk_wiz_0/inst/clk_out1]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 40 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/s1_pc[0]} {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/s1_pc[1]} {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/s1_pc[2]} {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/s1_pc[3]} {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/s1_pc[4]} {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/s1_pc[5]} {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/s1_pc[6]} {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/s1_pc[7]} {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/s1_pc[8]} {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/s1_pc[9]} {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/s1_pc[10]} {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/s1_pc[11]} {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/s1_pc[12]} {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/s1_pc[13]} {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/s1_pc[14]} {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/s1_pc[15]} {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/s1_pc[16]} {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/s1_pc[17]} {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/s1_pc[18]} {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/s1_pc[19]} {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/s1_pc[20]} {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/s1_pc[21]} {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/s1_pc[22]} {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/s1_pc[23]} {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/s1_pc[24]} {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/s1_pc[25]} {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/s1_pc[26]} {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/s1_pc[27]} {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/s1_pc[28]} {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/s1_pc[29]} {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/s1_pc[30]} {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/s1_pc[31]} {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/s1_pc[32]} {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/s1_pc[33]} {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/s1_pc[34]} {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/s1_pc[35]} {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/s1_pc[36]} {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/s1_pc[37]} {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/s1_pc[38]} {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/s1_pc[39]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 40 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/io_cpu_npc[0]} {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/io_cpu_npc[1]} {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/io_cpu_npc[2]} {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/io_cpu_npc[3]} {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/io_cpu_npc[4]} {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/io_cpu_npc[5]} {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/io_cpu_npc[6]} {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/io_cpu_npc[7]} {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/io_cpu_npc[8]} {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/io_cpu_npc[9]} {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/io_cpu_npc[10]} {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/io_cpu_npc[11]} {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/io_cpu_npc[12]} {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/io_cpu_npc[13]} {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/io_cpu_npc[14]} {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/io_cpu_npc[15]} {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/io_cpu_npc[16]} {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/io_cpu_npc[17]} {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/io_cpu_npc[18]} {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/io_cpu_npc[19]} {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/io_cpu_npc[20]} {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/io_cpu_npc[21]} {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/io_cpu_npc[22]} {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/io_cpu_npc[23]} {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/io_cpu_npc[24]} {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/io_cpu_npc[25]} {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/io_cpu_npc[26]} {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/io_cpu_npc[27]} {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/io_cpu_npc[28]} {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/io_cpu_npc[29]} {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/io_cpu_npc[30]} {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/io_cpu_npc[31]} {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/io_cpu_npc[32]} {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/io_cpu_npc[33]} {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/io_cpu_npc[34]} {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/io_cpu_npc[35]} {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/io_cpu_npc[36]} {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/io_cpu_npc[37]} {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/io_cpu_npc[38]} {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/io_cpu_npc[39]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 40 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/s2_pc[0]} {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/s2_pc[1]} {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/s2_pc[2]} {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/s2_pc[3]} {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/s2_pc[4]} {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/s2_pc[5]} {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/s2_pc[6]} {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/s2_pc[7]} {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/s2_pc[8]} {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/s2_pc[9]} {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/s2_pc[10]} {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/s2_pc[11]} {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/s2_pc[12]} {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/s2_pc[13]} {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/s2_pc[14]} {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/s2_pc[15]} {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/s2_pc[16]} {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/s2_pc[17]} {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/s2_pc[18]} {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/s2_pc[19]} {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/s2_pc[20]} {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/s2_pc[21]} {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/s2_pc[22]} {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/s2_pc[23]} {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/s2_pc[24]} {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/s2_pc[25]} {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/s2_pc[26]} {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/s2_pc[27]} {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/s2_pc[28]} {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/s2_pc[29]} {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/s2_pc[30]} {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/s2_pc[31]} {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/s2_pc[32]} {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/s2_pc[33]} {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/s2_pc[34]} {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/s2_pc[35]} {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/s2_pc[36]} {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/s2_pc[37]} {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/s2_pc[38]} {pardcore_i/LvNAFPGATop_0/inst/tile/frontend/s2_pc[39]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list pardcore_i/LvNAFPGATop_0/inst/tile/frontend/reset]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets pardcore_uncoreclk]
