ifneq ($(MAKECMDGOALS),clean) # ignore check for make clean

ifeq ($(PRM_SW_HOME),)
PRM_SW_HOME = $(shell echo $(abspath .) | sed -e 's+fpga/prm.*+fpga/prm+')
endif

PLATFORM ?= sim
PLATFORMS = $(shell ls $(PRM_SW_HOME)/platform/ | grep "platform-" | sed -e 's/platform-//')

ifeq ($(filter $(PLATFORMS), $(PLATFORM)), ) # PLATFORM must be valid
$(error Invalid PLATFORM. Supported: $(PLATFORMS))
endif

endif
